# sourcepp
set(SOURCEPP_USE_BSPPP OFF CACHE INTERNAL "" FORCE)
set(SOURCEPP_USE_DMXPP OFF CACHE INTERNAL "" FORCE)
set(SOURCEPP_USE_FSPP OFF CACHE INTERNAL "" FORCE)
set(SOURCEPP_USE_GAMEPP OFF CACHE INTERNAL "" FORCE)
set(SOURCEPP_USE_KVPP ON CACHE INTERNAL "" FORCE)
set(SOURCEPP_USE_MDLPP OFF CACHE INTERNAL "" FORCE)
set(SOURCEPP_USE_SNDPP OFF CACHE INTERNAL "" FORCE)
set(SOURCEPP_USE_STEAMPP OFF CACHE INTERNAL "" FORCE)
set(SOURCEPP_USE_TOOLPP OFF CACHE INTERNAL "" FORCE)
set(SOURCEPP_USE_VCRYPTPP OFF CACHE INTERNAL "" FORCE)
set(SOURCEPP_USE_VPKPP OFF CACHE INTERNAL "" FORCE)
set(SOURCEPP_USE_VTFPP OFF CACHE INTERNAL "" FORCE)
set(SOURCEPP_BUILD_WIN7_COMPAT OFF CACHE INTERNAL "" FORCE)
add_subdirectory("${CMAKE_CURRENT_LIST_DIR}/sourcepp")

# nlohmann-json
add_subdirectory("${CMAKE_CURRENT_LIST_DIR}/json")

# lntc_cpp
add_subdirectory("${CMAKE_CURRENT_LIST_DIR}/lntc_cpp")

# spdlog
add_subdirectory("${CMAKE_CURRENT_LIST_DIR}/spdlog")

# yaml-cpp
add_subdirectory("${CMAKE_CURRENT_LIST_DIR}/yaml-cpp")
